name = input("What is your full name")
age= input("What is your current age?")
citizenship_location = input("Which country are you a citizen in?")
entering_city = input("Which city is your starting location?")
destination = input("Which city are you going to?")
transport = input("What is your mode of transport?")
date = input("What is the date of your travel?")

print("********************************") 
print("Full Name: ", name)
print("Age: ", age)
print("Citizenship: " , citizenship_location)
print("Entering From ", entering_city)
print("Destination: " , destination)
print("Mode of Transport: " , transport)
print("Date: ", date)
print("********************************")
print("Have a safe trip!")